version: '3'

services:
  springboot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge