name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      environment:
      description: 'Skip test'
      required: true
      options: [true, false]

jobs:
  maven:
    uses: shierae/shared-workflows/.github/workflows/java-backend.yml@main
