name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maven:
    uses: shierae/shared-workflows/.github/workflows/java-backend.yml@main
