name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      skip_test:
        type: choice
        description: "Skip test"
        options:
        - true
        - false
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  maven:
    uses: shierae/shared-workflows/.github/workflows/java-backend.yml@main
    with:
      skip_test: ${{ inputs.skip_test }}
